# Generated by Django 4.2 on 2025-03-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_manufacturer_product_stock_product_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
