# Generated by Django 4.2 on 2025-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_rating_remove_product_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iphone', 'iPhone'), ('macbook', 'MacBook'), ('accessory', 'Phụ Kiện')], default='iphone', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
