# Generated by Django 5.2.2 on 2025-08-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_coupon_model'),
        ('home', '0008_coupon_qrorder_discount_amount_and_more'),
    ]

    operations = [
    ]
